require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Use Solid Queue as the background job backend (requires a `queue` db connection).
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Los enlaces de los correos: localhost, o el dominio del túnel si se da APP_HOST (p. ej. el de Cloudflare).
  config.action_mailer.default_url_options =
    ENV["APP_HOST"].present? ? { host: ENV["APP_HOST"], protocol: "https" } : { host: "localhost", port: 3000 }

  # En desarrollo los correos solo se ven en el log. Con SMTP_EN_DESARROLLO=1 salen de verdad por Gmail,
  # para probar con el túnel (bin/rails correo:prueba[tu@correo.com] confirma que la cuenta funciona).
  config.action_mailer.delivery_method = :test
  if ENV["SMTP_EN_DESARROLLO"] == "1"
    require Rails.root.join("config/gmail_smtp")
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.smtp_settings = GmailSmtp.settings
    config.action_mailer.raise_delivery_errors = true
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # Solo en desarrollo: sin esto, el WebSocket rechaza al teléfono que entra por la IP de la red local.
  config.action_cable.disable_request_forgery_protection = true

  # Túneles para probar desde el teléfono con HTTPS, que es lo que exigen el service worker y las
  # notificaciones push. Cada túnel estrena nombre, de ahí el patrón en vez de un host fijo.
  # Solo en desarrollo: en producción la lista de hosts se queda corta a propósito.
  config.hosts << /\A[a-z0-9-]+\.trycloudflare\.com\z/
  config.hosts << /\A[a-z0-9-]+\.ngrok(-free)?\.(app|io)\z/
  # Y la IP de la red local, para abrirlo desde el teléfono sin túnel (sin push: eso pide HTTPS).
  config.hosts << /\A192\.168\.\d{1,3}\.\d{1,3}\z/

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
